### ISSUE TITLE
ZapfDingbats icons not rendered on Debian Linux 9 (squeeze) - probably extraneous issue

### ISSUE THREAD

**Issue by balacode** [balacode/one-file-pdf#2]
The flower icon in the hello.pdf file is not rendered on Debian while using the default PDF viewer. But ZapfDingbats is a standard PDF font. Probably, this may be a Debian issue,  but I would appreciate any info if you experienced something similar on your OS, or PDF reader app. #

**Comment by Youmoo** [comment]
MacOS Preview doesn't render , either.

**Comment by balacode** [comment]
Thanks for that info.
