### ISSUE TITLE
PDF Metadata not properly encoded

### ISSUE THREAD

**Issue by BrianHoldsworth** [balacode/one-file-pdf#3]
The metadata fields like Title, Subject, Author, etc. are not shown in the rendered PDF because the /Type/Info object isn't properly delimited by the code.

To fix this, add call to pdf.writeObj near line 1081, like so:

![screen shot 2018-03-05 at 10 43 19 am](https://user-images.githubusercontent.com/731176/36984237-6ec4449e-2062-11e8-8aa5-3cc093b0dbcb.png)

**Comment by balacode** [comment]
Thank you very much! I have now added it. Could you share the code you used to catch this? It could be used to create some unit tests, as there are none now and PDFs are finicky.

**Comment by balacode** [comment]
Also, observe the block below. It looks wrong: writing antoehr /Info after the trailer. I'm going to dust off the PDF_Reference.pdf, and check the specs.

```go
	// write the trailer
	pdf.write("trailer\n<</Size %d/Root 1 0 R", len(pdf.objOffsets))
	if infoIndex > 0 {
		pdf.write("/Info %d 0 R", infoIndex)
	}
```

**Comment by BrianHoldsworth** [comment]
Yeah, I don't know how the "trailer" works but I took it to be a "Table of Contents" referring back to the /Type/Info object.

I am just doing simple ad-hoc testing. An automated test for a PDF generator will likely require a PDF parser.

An simpler alternative (no full parser) would be a test app designed to utilize all the generator's options, paired with simple `grep` based checking for the right strings in the output. This bug could have been caught by utilize pdf.SetDocTitle, then grep'ing the output for "/Type/Info/Title", right?

**Comment by balacode** [comment]
I'll look into writing some tests, starting with the metadata. For tests, I'm thinking of disabling compression so the PDF will just be a long string, then strip all whitespaces from both the check and the generated strings. Then just compare the two. It'll could be a brittle test, but not too much to worry. Just a matter of figuring the right PDF layout first.

**Comment by balacode** [comment]
I checked some specs. The /Info I mentioned is part of the trailer, along with /Size and /Root, so It's OK for it to be there. It's just an index in the trailer to locate the info.
