### ISSUE TITLE
No support for simple color (RGB) PNG images

### ISSUE THREAD

**Issue by BrianHoldsworth** [balacode/one-file-pdf#5]
I have been experimenting with using color PNG images with DrawImage() method, and so far found this to work with just a two line change. Is there much more than this needed in order to officially support color images instead of grayscale?

![screen shot 2018-03-11 at 10 34 59 pm](https://user-images.githubusercontent.com/731176/37263001-8c83537a-257c-11e8-9798-ad886df0d04c.png)
![screen shot 2018-03-11 at 10 35 20 pm](https://user-images.githubusercontent.com/731176/37263006-92ac5bd4-257c-11e8-8b38-c2abd62e453f.png)

**Comment by balacode** [comment]
Hi! Here's an update on what I found: whether a color or gray image, drawing images without transparency is clear, but a PNG with transparency gets complicated. In `/ColorSpace/DeviceRGB/` I'm seeing only R, G, and B components written to the PDF's data, but not the Alpha. The crude way around this to blend the alpha from the image with the background color. But PDF1.4 introduced transparency, and it's simple for text and shapes, but not images. So I'm researching how it should be done for images.

**Comment by BrianHoldsworth** [comment]
Hi. I looked into the same thing, but managed to convince myself that the call to .RGBA() actually does the alpha multiplication of the RGB values for you. So those can be used directly.

Take look at the changes I annotated in the pull request (which you cannot merge cause it is based on your code from several days back). But anyway it is working for me with B&W and Color PNG images now, and it needs some more testing to verify GIF and JPG.

**Comment by balacode** [comment]
I'm just learning the GIT pull process. It's better I view the commit changes you've made on your own branch, not from my branch's perspective.

I think there won't be any problem with JPGs. About the alpha. When I tried a solid PNG, it was drawn properly, but when I tried a PNG with transparency, it treated the transparent pixels as black. I noticed where the alpha is 0, the RGB are also 0 (i.e. black). So if it blends the color, what color is it blending against? Is there somewhere you can set the background color, so it blends against white? I'll continue later tomorrow. Thank you very much for the help.

**Comment by BrianHoldsworth** [comment]
Unfortunately, I forked after your recent changes, then committed what I have been testing locally. So the diff on my branch is just as ugly as the diff on yours. Best thing is just look at those screenshots of my changes in the pull request, then close the pull request without merging it.

**Comment by BrianHoldsworth** [comment]
On the Alpha blending, I think golang is doing the right thing, but there is no background color defined for the document. Might be there needs to be a setter for the document background color, then substitute that color whenever ALPHA == 0.0.

**Comment by balacode** [comment]
Ah, yes I'll use the screenshots and also look at your copy directly. Even if the document has no background color, there should be a place where we can specify the background color in the Golang's image before reading the RGBA, right? That should be in the docs somewhere.

**Comment by BrianHoldsworth** [comment]
I didn't find it in the docs. It would be overkill to try to do compositing inside a simple-by-design pdf generator. If I wanted graphics that fancy, I'd probably rely on HTML5 Canvas or I'd pre-render the composite image and then just dumb copy it to the pdf page.
