### ISSUE TITLE
How to support Unicode in the PDF format?

### ISSUE THREAD

**Issue by balacode** [balacode/one-file-pdf#8]
Unicode support is essential in modern software, so we are going to implement some kind of Unicode support in this PDF writer. If you know or can link to any information about font embedding (to enable Unicode) or just referencing external fonts installed on the system in order to use Unicode, please let me know. Thanks for your attention.

**Comment by mikamiel** [comment]
I believe, you've seen it already, but just in case, https://github.com/signintech/gopdf package has font embedding implemented (without any external dependences).

**Comment by balacode** [comment]
Thanks for pointing me to this good PDF package and your contributions to it. I'll study how it works. That should answer my questions. It's easy to miss a good project among the many options.

**Comment by mikamiel** [comment]
Waiting for font embedding feature in your neat package ;)

**Comment by balacode** [comment]
Closing the issue because all my questions have been answered. Now working on a compact implementation.

**Comment by mycalf** [comment]
@balacode  When can I support this feature?
